### PR TITLE
select destination directories depending on $XDG_CONFIG_HOME following https://unix.stackexchange.com/questions/312988/understanding-home-configuration-file-locations-config-and-local-sha

### LINKED ISSUE #6: Destination directories changed in recent linux distributions
The scripts install the files to `~/.openra/*`. In newer distributions such as Debian or Linux Mint (and probably also Ubuntu) the files are not found by the game because it expects them at `~/.config/openra/*`.

So the scripts must be either changed to generally use the new location or to figure out which of the two options to use in a certain case.

### PR DESCRIPTION
**Pull request by dr-death2**
fixes #6

---
This change is [Reviewable](https://reviewable.io/reviews/walkman100/openra-install-guide/7)

### CODE REVIEW

**Comment by dr-death2** [comment]
fixes  #5 
fixes the issue with "Direct Download" of `Dune_2000_Gruntmods_Edition_Cutscenes.exe` mentioned in a comment in https://github.com/Walkman100/OpenRA-Install-Guide/issues/1#issuecomment-222339414

**Comment by ghost** [comment]
i was about to make this PR myself, but seems you were first

**Comment by Walkman100** [comment]
Finally looking to play a bit of RA again, seems there's a fair amount of updating to do. The first 3 commits on this PR I'm happy with, thank you for the updated links, but I want to test the full install stuff separately, so I'll merge just those 3 for now.

**Comment by Walkman100** [comment]
Also, seems XWIS updated their RA2 link again: http://xwis.net/Dl/Red-Alert-2-Multiplayer.exe

**Comment by Walkman100** [comment]
Also, it looks like you're using `$XDG_CONFIG_HOME` incorrectly, should that variable be used if it exists? instead of defaulting to $HOME? I'm not 100% sure, as I've never encountered it being set.

**Comment by Walkman100** [comment]
Merged first 3 ending with https://github.com/Walkman100/OpenRA-Install-Guide/commit/954c76e61c18913a78729a05d41c488abeabdb51.

**Comment by dr-death2** [comment]
> but I want to test the full install stuff separately

@Walkman100: let me know if i can help you in testing by explaining or refactoring or in any other way

**Pull request closed without merging**
